import { CSSProperties } from "react";

export const Colors = {
  navy: "#0f1f3d",
  navyLight: "#1a3560",
  blue: "#3b5bdb",
  blueDim: "#4c6ef5",
  blueLight: "#eef2ff",
  gray50: "#f8fafc",
  gray100: "#f1f5f9",
  gray200: "#e2e8f0",
  gray300: "#cbd5e1",
  gray400: "#94a3b8",
  gray500: "#64748b",
  gray600: "#475569",
  gray700: "#334155",
  gray800: "#1e293b",
  white: "#ffffff",
  red: "#c0392b",
  orange: "#d35400",
  yellow: "#b8860b",
  green: "#1a7f4e",
};
export const s: Record<string, CSSProperties> = {
  nav: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
    background: "rgba(255,255,255,0.97)",
    backdropFilter: "blur(8px)",
    borderBottom: `1px solid ${Colors.gray200}`,
    padding: "0 2rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: 64,
  },
  navBrand: {
    fontFamily: "'Courier New', monospace",
    fontWeight: 700,
    fontSize: "1.05rem",
    color: Colors.navy,
    textDecoration: "none",
  },
  navLinks: {
    display: "flex",
    gap: "1.4rem",
    listStyle: "none",
    margin: 0,
    padding: 0,
    flexWrap: "wrap",
  },
  navLink: {
    color: Colors.gray600,
    textDecoration: "none",
    fontSize: "0.82rem",
    fontWeight: 500,
    letterSpacing: "0.2px",
    cursor: "pointer",
    transition: "color 0.15s",
  },
  section: { padding: "5rem 2rem" },
  sectionAlt: { padding: "5rem 2rem", background: Colors.gray50 },
  container: { maxWidth: 1080, margin: "0 auto" },
  sectionLabel: {
    fontFamily: "'Courier New', monospace",
    color: Colors.blue,
    fontSize: "0.75rem",
    letterSpacing: "2px",
    fontWeight: 700,
    textTransform: "uppercase",
    marginBottom: "0.4rem",
  },
  sectionTitle: {
    color: Colors.navy,
    fontSize: "clamp(1.6rem, 3vw, 2.1rem)",
    fontWeight: 800,
    margin: "0 0 0.4rem",
  },
  sectionSub: {
    color: Colors.gray500,
    fontSize: "0.95rem",
    margin: "0 0 2rem",
  },
  divider: {
    width: 44,
    height: 3,
    background: Colors.blue,
    borderRadius: 2,
    margin: "0.6rem 0 2.5rem",
  },
  card: {
    background: Colors.white,
    borderRadius: 16,
    padding: "2.5rem",
    border: `1px solid ${Colors.gray200}`,
    boxShadow:
      "0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)",
    transition: "box-shadow 0.2s, transform 0.2s",
  },
  grid2: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))",
    gap: "2rem",
  },
  grid3: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "1.25rem",
  },
  grid4: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(175px, 1fr))",
    gap: "1rem",
  },
  badge: {
    display: "inline-block",
    padding: "0.2rem 0.6rem",
    borderRadius: 20,
    fontSize: "0.72rem",
    fontWeight: 600,
  },
  tag: {
    display: "inline-block",
    background: "#f1f5f9",
    color: "#475569",
    padding: "0.5rem 1rem",
    borderRadius: 6,
    fontSize: "0.88rem",
    fontWeight: 500,
    marginRight: "0.6rem",
    marginBottom: "0.75rem",
    border: "1px solid #e2e8f0",
  },
  contactInput: {
    width: "100%",
    padding: "0.72rem 1rem",
    border: `1px solid ${Colors.gray200}`,
    borderRadius: 6,
    fontSize: "0.93rem",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
    background: Colors.white,
    color: Colors.gray800,
    transition: "border-color 0.2s",
  },
  btnPrimary: {
    background: Colors.blue,
    color: Colors.white,
    border: "none",
    padding: "0.72rem 1.8rem",
    borderRadius: 6,
    fontWeight: 600,
    fontSize: "0.93rem",
    cursor: "pointer",
    textDecoration: "none",
    display: "inline-block",
  },
  btnOutline: {
    background: "transparent",
    color: "rgba(255,255,255,0.85)",
    border: "1.5px solid rgba(255,255,255,0.3)",
    padding: "0.72rem 1.8rem",
    borderRadius: 6,
    fontWeight: 600,
    fontSize: "0.93rem",
    cursor: "pointer",
    textDecoration: "none",
    display: "inline-block",
    marginLeft: "0.75rem",
  },
  iconLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.4rem",
    color: "rgba(255,255,255,0.7)",
    textDecoration: "none",
    fontSize: "0.85rem",
    fontWeight: 500,
    padding: "0.4rem 0.8rem",
    borderRadius: 6,
    border: "1px solid rgba(255,255,255,0.2)",
    transition: "background 0.15s",
  },
};
export const severityColor = (d: string) =>
  ({
    Critical: Colors.red,
    High: Colors.orange,
    Medium: Colors.yellow,
    Low: Colors.green,
  })[d] || Colors.gray400;
export const diffColor = (d: string) =>
  ({
    Easy: Colors.green,
    Medium: Colors.yellow,
    Hard: Colors.orange,
    Insane: Colors.red,
  })[d] || Colors.gray400;
